/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lostitemproject;

import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author POOM
 */
public class LocationChoicePanel extends javax.swing.JPanel {
//    private JPanel panelInScroll;
    private String[] locationList;
    private JCheckBox[] allCheckBox;
    /**
     * Creates new form LocationChoicePanel
     */
    public LocationChoicePanel() throws SQLException, ClassNotFoundException {
        DBManagement dbm = new DBManagement();
        dbm.createConnection();
        locationList = dbm.queryLocation();
        dbm.disconnect();
        allCheckBox = new JCheckBox[locationList.length];
        initComponents();
        this.setSize(100, locationList.length*20);
        this.setLayout(new BoxLayout(this,BoxLayout.Y_AXIS));
        for(int i=0;i<locationList.length;i++){
            allCheckBox[i] = new JCheckBox(locationList[i]); 
            this.add(allCheckBox[i]);
        }
        this.setSize(100,400);
        this.revalidate();
        this.repaint();
        
    }

    public JCheckBox[] getAllCheckBox() {
        return allCheckBox;
    }

    public void setAllCheckBox(JCheckBox[] allCheckBox) {
        this.allCheckBox = allCheckBox;
    }

    public String[] getLocationList() {
        return locationList;
    }

    public void setLocationList(String[] locationList) {
        this.locationList = locationList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
