/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lostitemproject;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Kimmy
 */
public class ViewDetailGUI extends javax.swing.JPanel {
    private LostItem focusItem;
    private String textNull = "-";
    /**
     * Creates new form ViewDetailGUI
     */
    public ViewDetailGUI() {
        initComponents();
    }

    ViewDetailGUI(LostItem focusItem) {
        this.focusItem = focusItem;
        initComponents();
        try{
            userNameText.setText(focusItem.getOwnerName());
            picture.setIcon(new ImageIcon(focusItem.getImg().getScaledInstance(302, 197, Image.SCALE_SMOOTH)));
        }catch(NullPointerException ex){
            ex.printStackTrace();
            System.out.println("img find problem");
        }
        
        //To change body of generated methods, choose Tools | Templates.
    }

    public JButton getBackBtn() {
        return backBtn;
    }

    public void setBackBtn(JButton backBtn) {
        this.backBtn = backBtn;
    }


    public JLabel getDateTextStart() {
        return dateTextEnd;
    }

    public void setDateTextStart(JLabel dateTextStart) {
        this.dateTextEnd = dateTextStart;
    }

    public JLabel getDescriptionText() {
        return descriptionText;
    }

    public void setDescriptionText(JLabel descriptionText) {
        this.descriptionText = descriptionText;
    }

    public JLabel getLocationText() {
        return locationText;
    }

    public void setLocationText(JLabel locationText) {
        this.locationText = locationText;
    }

    public JLabel getLostItemText() {
        return lostItemText;
    }

    public void setLostItemText(JLabel lostItemText) {
        this.lostItemText = lostItemText;
    }

    public JLabel getNameText() {
        return nameText;
    }

    public void setNameText(JLabel nameText) {
        this.nameText = nameText;
    }

    public JLabel getPicture() {
        return picture;
    }

    public void setPicture(JLabel picture) {
        this.picture = picture;
    }

    public JLabel getUserNameText() {
        return userNameText;
    }

    public void setUserNameText(JLabel userNameText) {
        this.userNameText = userNameText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detail = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        lostItem = new javax.swing.JLabel();
        descriptionText = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        lostItemText = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        locationText = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        dateTextEnd = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userNameText = new javax.swing.JLabel();
        status = new javax.swing.JButton();
        dateTextStart1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();

        setLayout(null);

        detail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        detail.setText("ดูรายละเอียด");
        add(detail);
        detail.setBounds(380, 30, 128, 29);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("ชื่่อของหาย");
        add(name);
        name.setBounds(190, 280, 65, 25);

        description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        description.setText("คำอธิบาย");
        add(description);
        description.setBounds(190, 330, 56, 17);

        lostItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lostItem.setText("หมวดหมู่");
        add(lostItem);
        lostItem.setBounds(190, 370, 50, 17);

        descriptionText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(descriptionText);
        descriptionText.setBounds(300, 330, 339, 28);
        descriptionText.setText(focusItem.getItemDescription());

        nameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(nameText);
        nameText.setBounds(300, 280, 339, 28);
        nameText.setText(focusItem.getItemName());

        lostItemText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lostItemText);
        lostItemText.setBounds(300, 370, 171, 28);
        lostItemText.setText(focusItem.getCate());

        location.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        location.setText("สถานที่");
        add(location);
        location.setBounds(490, 370, 43, 17);

        locationText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(locationText);
        locationText.setBounds(550, 370, 89, 28);
        locationText.setText(focusItem.getStatus().getLocationName());

        picture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(picture);
        picture.setBounds(310, 70, 302, 197);

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setText("วันที่พบของ");
        add(date);
        date.setBounds(190, 450, 74, 17);

        dateTextEnd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(dateTextEnd);
        dateTextEnd.setBounds(300, 450, 339, 28);
        dateTextEnd.setText(textNull);

        backBtn.setText("ย้อนกลับ");
        add(backBtn);
        backBtn.setBounds(320, 500, 92, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lostitemproject.image/user (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(32, 32));
        jLabel1.setMinimumSize(new java.awt.Dimension(32, 32));
        add(jLabel1);
        jLabel1.setBounds(640, 13, 32, 32);

        userNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(userNameText);
        userNameText.setBounds(684, 13, 154, 32);

        status.setText("เปลี่ยนสถานะ");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        add(status);
        status.setBounds(430, 500, 120, 33);

        dateTextStart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(dateTextStart1);
        dateTextStart1.setBounds(300, 410, 339, 28);
        dateTextStart1.setText(focusItem.getDateStart().toString());

        date1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date1.setText("วันที่ของหาย");
        add(date1);
        date1.setBounds(190, 410, 74, 17);
    }// </editor-fold>//GEN-END:initComponents

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        ImageIcon icon = new ImageIcon(focusItem.getImg().getScaledInstance(302, 197, Image.SCALE_SMOOTH));
                JOptionPane.showMessageDialog(
                        null,
                        ""+focusItem.getItemName(),
                        "Hello", JOptionPane.INFORMATION_MESSAGE,
                        icon);
                
    }//GEN-LAST:event_statusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel dateTextEnd;
    private javax.swing.JLabel dateTextStart1;
    private javax.swing.JLabel description;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JLabel detail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel location;
    private javax.swing.JLabel locationText;
    private javax.swing.JLabel lostItem;
    private javax.swing.JLabel lostItemText;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel picture;
    private javax.swing.JButton status;
    private javax.swing.JLabel userNameText;
    // End of variables declaration//GEN-END:variables
}
