/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lostitemproject;

import java.awt.Component;
import java.awt.FlowLayout;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author POOM
 */
public class ViewLostItemGUI extends javax.swing.JPanel {
//    private JPanel subPanel;
    private LostItem focusItem;
    private EachItemGUI[] allItemShow;
    private String pageToGo;
    private Account acc;
    /**
     * Creates new form ViewLostItemGUI
     */
    public ViewLostItemGUI(Account acc) throws InterruptedException, ClassNotFoundException, SQLException {
        DBManagement dbm = new DBManagement();
        dbm.createConnection();      
        LostItem[] item = dbm.queryItem("","DESC");
        this.acc = acc;
        
        allItemShow = new EachItemGUI[item.length];
        JPanel subPanel = new JPanel();
        subPanel.setSize(500, item.length*120);
        for(int i=0;i<item.length;i++){
            EachItemGUI each = new EachItemGUI(item[i]);
            subPanel.add(each);
            allItemShow[i]=each;
        }
        subPanel.setLayout(new BoxLayout(subPanel,BoxLayout.Y_AXIS));
        initComponents();
        ScrollItemList.setViewportView(subPanel);
        ScrollItemList.getVerticalScrollBar().setUnitIncrement(16);
        
//        while(pageToGo==null){
//            Thread.sleep(1000);
//        }
//        ScrollItemList.revalidate();
//        ScrollItemList.repaint();
        
        
    }

    public String getPageToGo() {
        return pageToGo;
    }

    public void setPageToGo(String pageToGo) {
        this.pageToGo = pageToGo;
    }

    public LostItem getFocusItem() {
        return focusItem;
    }

    public void setFocusItem(LostItem focusItem) {
        this.focusItem = focusItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollItemList = new javax.swing.JScrollPane();

        ScrollItemList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollItemList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ScrollItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(ScrollItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollItemList;
    // End of variables declaration//GEN-END:variables

    public void update() {
        for(int i=0;i<allItemShow.length;i++){
            if(allItemShow[i].getPageToGo()!=null){
                pageToGo="viewDetails";
                focusItem=allItemShow[i].getItem();
                break;
            }
        }
    }
}
