package lostitemproject;

import java.awt.Component;
import java.awt.FlowLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class ViewLostItemGUI extends javax.swing.JPanel {
//    private JPanel subPanel;
    private LostItem focusItem;
    private EachItemGUI[] allItemShow;
    private String pageToGo;
    private Account acc;
    private DBManagement dbm;
    /**
     * Creates new form ViewLostItemGUI
     */
    public ViewLostItemGUI(Account acc) throws InterruptedException, ClassNotFoundException, SQLException {
        dbm = new DBManagement();
        dbm.createConnection();      
        LostItem[] item = dbm.queryItem("","DESC");
        this.acc = acc;
        
        allItemShow = new EachItemGUI[item.length];
        JPanel subPanel = new JPanel();
        subPanel.setSize(708, item.length*140);
        for(int i=0;i<item.length;i++){
            EachItemGUI each = new EachItemGUI(item[i]);
            subPanel.add(each);
            allItemShow[i]=each;
        }
        subPanel.setLayout(new BoxLayout(subPanel,BoxLayout.Y_AXIS));
        initComponents();
        ScrollItemList.setViewportView(subPanel);
        ScrollItemList.getVerticalScrollBar().setUnitIncrement(16);
        
//        while(pageToGo==null){
//            Thread.sleep(1000);
//        }
//        ScrollItemList.revalidate();
//        ScrollItemList.repaint();
        
        
    }

    public String getPageToGo() {
        return pageToGo;
    }

    public void setPageToGo(String pageToGo) {
        this.pageToGo = pageToGo;
    }

    public LostItem getFocusItem() {
        return focusItem;
    }

    public void setFocusItem(LostItem focusItem) {
        this.focusItem = focusItem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollItemList = new javax.swing.JScrollPane();
        searchBtn = new javax.swing.JButton();
        cateList = new javax.swing.JComboBox<>();
        locateList = new javax.swing.JComboBox<>();
        statusList = new javax.swing.JComboBox<>();
        orderByList = new javax.swing.JComboBox<>();
        addLostItembtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        ScrollItemList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollItemList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBtn.setText("ค้นหา");
        searchBtn.setMaximumSize(new java.awt.Dimension(65, 25));
        searchBtn.setMinimumSize(new java.awt.Dimension(65, 25));
        searchBtn.setName(""); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        cateList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ทั้งหมด", "อุปกรณ์อิเล็กทรอนิกส์", "เครื่องแต่งกาย", "กระเป๋า", "กุญแจ", "อื่นๆ" }));

        DBManagement dbm = new DBManagement();
        try{
            dbm.createConnection();
            String[] locate = dbm.queryLocation();
            locateList.setMaximumRowCount(60);
            String[] temp = new String[locate.length+1];
            temp[0]="ทั้งหมด";
            for(int i=1;i<temp.length;i++){
                temp[i]=locate[i-1];
            }
            locateList.setModel(new javax.swing.DefaultComboBoxModel<>(temp));
            dbm.disconnect();
        }catch(Exception e){
            e.printStackTrace();
        }

        statusList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ทั้งหมด", "กำลังหา", "พบแล้ว", "ได้รับคืนแล้ว" }));

        orderByList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ใหม่-เก่า", "เก่า-ใหม่" }));

        addLostItembtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addLostItembtn.setText("แจ้งของหาย");
        addLostItembtn.setMaximumSize(new java.awt.Dimension(65, 25));
        addLostItembtn.setMinimumSize(new java.awt.Dimension(65, 25));
        addLostItembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLostItembtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("หมวดหมู่");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("สถานที่");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("สถานะ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ลำดับ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("LOSING THINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cateList, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(locateList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderByList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(ScrollItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLostItembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(statusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(orderByList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollItemList, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addLostItembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            dbm.createConnection();
            String condition = "";
            if(cateList.getSelectedIndex()!=0){
                condition+=" AND Cate_cateId="+cateList.getSelectedIndex();
            }
            if(locateList.getSelectedIndex()!=0){        
                condition+=" AND Location_locationId="+locateList.getSelectedIndex();                   
            }
            if(statusList.getSelectedIndex()!=0){
                condition+=" AND itemstatus.Status_statusId="+statusList.getSelectedIndex();
            }
            String orderBy=(orderByList.getSelectedIndex()==0?"DESC":"ASC");
            LostItem[] item = dbm.queryItem(condition,orderBy);
            this.acc = acc;
            
            allItemShow = new EachItemGUI[item.length];
            JPanel subPanel = new JPanel();
            subPanel.setSize(500, item.length*120);
            for(int i=0;i<item.length;i++){
                EachItemGUI each = new EachItemGUI(item[i]);
                subPanel.add(each);
                allItemShow[i]=each;
            }
            subPanel.setLayout(new BoxLayout(subPanel,BoxLayout.Y_AXIS));
            ScrollItemList.setViewportView(subPanel);
            ScrollItemList.revalidate();
            ScrollItemList.repaint();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewLostItemGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewLostItemGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ViewLostItemGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void addLostItembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLostItembtnActionPerformed
        pageToGo="addLostItem";
    }//GEN-LAST:event_addLostItembtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollItemList;
    private javax.swing.JButton addLostItembtn;
    private javax.swing.JComboBox<String> cateList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> locateList;
    private javax.swing.JComboBox<String> orderByList;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> statusList;
    // End of variables declaration//GEN-END:variables

    public void update() {
        for(int i=0;i<allItemShow.length;i++){
            if(allItemShow[i]==null){
                System.out.println("data changed abort update!");
                break;
            }
            if(allItemShow[i].getPageToGo()!=null){
                pageToGo="viewDetails";
                focusItem=allItemShow[i].getItem();
                break;
            }
        }
    }
}
